version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: inet_test
      POSTGRES_PASSWORD: inet_test
      POSTGRES_DB: inet_test
    volumes:
      - pg_vol:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 55432:5432

volumes:
  pg_vol:
